apiVersion: v1
kind: Service
metadata:
  name: app-service-clusterip
  namespace: dev
  labels:
    name: app-service-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: myapp
      type: frontend