apiVersion: v1
kind: Service
metadata:
  name: app-service1
  labels:
    name: app-service1
    type: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30009
      targetPort: 80
  selector:
    app: myapp
    type: frontend